modLoader="javafml"
loaderVersion="[40,)"
license="The Apache License, Version 2.0"
issueTrackerURL="http://github.com/MelanX/ExNaturae/issues"

[[mods]]
modId="exnaturae"
version="${file.jarVersion}"
displayName="Ex Naturae"
displayURL="www.curseforge.com/members/melanx/"
credits="Translators: 19PixelsPlaced (French), Chosen (Russian), DrMrPotatoe (Spanish)"
authors="MelanX"
description="""
An addon to combine Ex Nihilo: Sequentia and Botania
"""

[[dependencies.exnaturae]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.2-433,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="excompressum"
    mandatory=false
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"