modLoader="javafml"
loaderVersion="[${fml},)"
license="The Apache License, Version 2.0"
issueTrackerURL="http://github.com/MelanX/ExNaturae/issues"

[[mods]]
modId="exnaturae"
version="${version}"
displayName="Ex Naturae"
displayURL="www.curseforge.com/members/melanx/"
credits="Translators: 19PixelsPlaced (French), Chosen (Russian), DrMrPotatoe (Spanish)"
authors="MelanX"
description="""
An addon to combine Ex Nihilo: Sequentia and Botania
"""

[[dependencies.exnaturae]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.2-4.2.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="botania"
    mandatory=true
    versionRange="[1.19.2-439,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnaturae]]
    modId="excompressum"
    mandatory=false
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"